### ISSUE TITLE
服务发布失败:tars.tarsregistry.QueryObj|no such active connection invoker

### ISSUE THREAD

**Issue by leeqx** [TarsCloud/Tars#309]
### What language are you using?
 cpp
 
### What operating system (Linux, Ubuntu, …) and version?
 
 centos in docker
### What runtime / compiler are you using (e.g. jdk version or version of gcc)
 
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
上传tarsstat.tgz 成功，点击发布之后提示 `服务发布失败:tars.tarsregistry.QueryObj|no such active connection invoker`
```shell
[root@3881d3f3baa1 workerspace]# netstat -anp|grep tars
tcp        0      0 172.17.0.2:19385        0.0.0.0:*               LISTEN      8274/tarsnode
tcp        0      0 127.0.0.1:19385         0.0.0.0:*               LISTEN      8274/tarsnode
tcp        0      0 172.17.0.2:19386        0.0.0.0:*               LISTEN      8274/tarsnode
tcp        0      0 172.17.0.2:12000        0.0.0.0:*               LISTEN      8241/tarsAdminRegis
tcp        0      0 172.17.0.2:17890        0.0.0.0:*               LISTEN      8232/tarsregistry
tcp        0      0 172.17.0.2:17891        0.0.0.0:*               LISTEN      8232/tarsregistry
tcp        0      0 172.17.0.2:10000        0.0.0.0:*               LISTEN      8282/tarspatch
tcp        0      0 127.0.0.1:10000         0.0.0.0:*               LISTEN      8282/tarspatch
tcp        0      0 172.17.0.2:10001        0.0.0.0:*               LISTEN      8261/tarsconfig
tcp        0      0 127.0.0.1:10001         0.0.0.0:*               LISTEN      8261/tarsconfig
tcp        0      0 172.17.0.2:46862        172.17.0.2:3306         ESTABLISHED 8232/tarsregistry
tcp        0      0 172.17.0.2:47116        172.17.0.2:3306         ESTABLISHED 8232/tarsregistry
tcp        0      0 172.17.0.2:40588        172.17.0.2:19386        ESTABLISHED 8261/tarsconfig
tcp        0      0 172.17.0.2:47088        172.17.0.2:3306         ESTABLISHED 8232/tarsregistry
tcp        0      0 172.17.0.2:47130        172.17.0.2:3306         ESTABLISHED 8232/tarsregistry
tcp        0      0 172.17.0.2:46850        172.17.0.2:3306         ESTABLISHED 8232/tarsregistry
tcp        0      0 172.17.0.2:46822        172.17.0.2:3306         ESTABLISHED 8232/tarsregistry
tcp        0      0 172.17.0.2:47102        172.17.0.2:3306         ESTABLISHED 8232/tarsregistry
tcp        0      0 172.17.0.2:46810        172.17.0.2:3306         ESTABLISHED 8232/tarsregistry
tcp        0      0 172.17.0.2:47146        172.17.0.2:3306         ESTABLISHED 8232/tarsregistry
tcp        0      0 172.17.0.2:46834        172.17.0.2:3306         ESTABLISHED 8232/tarsregistry
tcp        0      0 172.17.0.2:19386        172.17.0.2:40590        ESTABLISHED 8274/tarsnode
tcp        0      0 172.17.0.2:19386        172.17.0.2:40588        ESTABLISHED 8274/tarsnode
tcp        0      0 172.17.0.2:40590        172.17.0.2:19386        ESTABLISHED 8282/tarspatch
tcp        0      0 172.17.0.2:46848        172.17.0.2:3306         ESTABLISHED 8232/tarsregistry
tcp        0      0 172.17.0.2:46824        172.17.0.2:3306         ESTABLISHED 8232/tarsregistry
tcp        0      0 172.17.0.2:46864        172.17.0.2:3306         ESTABLISHED 8232/tarsregistry
tcp        0      0 172.17.0.2:46806        172.17.0.2:3306         ESTABLISHED 8241/tarsAdminRegis
tcp        0      0 172.17.0.2:46846        172.17.0.2:3306         ESTABLISHED 8232/tarsregistry
```

对应的tars进程：
```shell
root      8232     1  0 10:41 pts/0    00:00:06 /usr/local/app/tars/tarsregistry/bin/tarsregistry --config=/usr/local/app/tars/tarsregistry/conf/tarsregistry.conf
root      8241     1  0 10:41 pts/0    00:00:02 /usr/local/app/tars/tarsAdminRegistry/bin/tarsAdminRegistry --config=/usr/local/app/tars/tarsAdminRegistry/conf/adminregistry.conf
root      8261     1  0 10:41 pts/0    00:00:02 /usr/local/app/tars/tarsconfig/bin/tarsconfig --config=/usr/local/app/tars/tarsconfig/conf/tarsconfig.conf
root      8274     1  0 10:41 ?        00:00:03 /usr/local/app/tars/tarsnode/bin/tarsnode --locator=tars.tarsregistry.QueryObj@tcp -h 172.17.0.2 -p 17890 --config=/usr/local/app/tars/tarsnode/conf/tarsnode.conf
root      8282     1  0 10:41 pts/0    00:00:02 /usr/local/app/tars/tarspatch/bin/tarspatch --config=/usr/local/app/tars/tarspatch/conf/tarspatch.conf
root      8373     1  0 10:41 ?        00:00:00 rsync --address=172.17.0.2 --daemon --config=/usr/local/app/tars/tarspatch/conf/rsync.conf
```

resin 日志：
```log
018-09-11 10:42:29.729|INFO|ConfigService.java|190|deleteUnusedNodeConfigFiles|delete 0 unused node config file(s)
2018-09-11 10:42:29.730|INFO|ScheduleService.java|35|checkUnusedConfigFiles|delete 0 unused node config file(s)
2018-09-11 10:42:30.323|INFO|VariablesInterceptor.java|43|preHandle|  traceUrl is
2018-09-11 10:42:30.410|INFO|ConfigService.java|190|deleteUnusedNodeConfigFiles|delete 0 unused node config file(s)
2018-09-11 10:42:30.411|INFO|ScheduleService.java|35|checkUnusedConfigFiles|delete 0 unused node config file(s)
2018-09-11 10:42:32.199|INFO|VariablesInterceptor.java|43|preHandle|  traceUrl is
2018-09-11 10:42:32.346|INFO|AdminService.java|144|lambda$addTask$1|item=8aedfefc549a43d0bd5527054ed13a43, applicaiton=tars, server_name=tarsstat, node_name=172.17.0.2, command=patch_tars, parameters={patch_id=52, bak_flag=0, update_text=}
2018-09-11 10:42:32.491|INFO|WrappedController.java|83|handleException|exception intercepted, uri=/pages/server/api/add_task, isajax=true
com.qq.tars.rpc.exc.NoConnectionException: tars.tarsregistry.QueryObj|no such active connection invoker
        at com.qq.tars.client.ObjectProxy.invoke(ObjectProxy.java:101)
        at com.sun.proxy.$Proxy108.findObjectByIdInSameGroup(Unknown Source)
        at com.qq.tars.support.query.QueryHelper.getServerNodes(QueryHelper.java:57)
        at com.qq.tars.client.ObjectProxyFactory.updateServantEndpoints(ObjectProxyFactory.java:123)
        at com.qq.tars.client.ObjectProxyFactory.getObjectProxy(ObjectProxyFactory.java:53)
        at com.qq.tars.client.ServantProxyFactory.getServantProxy(ServantProxyFactory.java:46)
        at com.qq.tars.client.Communicator.stringToProxy(Communicator.java:73)
        at com.qq.tars.client.Communicator.stringToProxy(Communicator.java:56)
        at com.qq.tars.service.admin.AdminService.getAdminRegPrx(AdminService.java:70)
        at com.qq.tars.service.admin.AdminService.addTask(AdminService.java:150)
        at com.qq.tars.service.task.TaskService.addTask(TaskService.java:76)
        at com.qq.tars.web.controller.TaskController.addTask(TaskController.java:50)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:777)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:706)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:943)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:877)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:868)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:159)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:97)
        at com.caucho.server.dispatch.ServletFilterChain.doFilter(ServletFilterChain.java:109)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilte
```

**Comment by leeqx** [comment]
哪位帮忙看看
![image](https://user-images.githubusercontent.com/931925/45336553-a616fd80-b5b6-11e8-956d-a50bd2678609.png)

**Comment by dpp2009** [comment]
tarsnode  tarsregistry  应该只有一个实例

**Comment by leeqx** [comment]
搞定了是web/tars.conf 配置-h 与后面的ip没有空格导致的
