### ISSUE TITLE
web管理平台 报系统内部错误。系统内部错误  common.reTry

### ISSUE THREAD

**Issue by iiCircle** [TarsCloud/Tars#314]
系统内部错误

common.reTry

**Comment by ypingcn** [comment]
pm2 logs tars-node-web --lines 1000
可以看下 web 平台的日志，是不是数据库没连上或者少了哪个表

**Comment by iiCircle** [comment]
好的。谢谢，  怎么确定少哪个表了呢？  总共有多少个表 我还不清楚，没有配置成功过。

**Comment by ypingcn** [comment]
@iiCircle 具体看日志吧，最近装的时候会提示少 db_tars.t_server_notifys ，issue 里有解决的 SQL 语句
#152

**Comment by iiCircle** [comment]
0|tars-nod | Wed, 26 Sep 2018 09:58:21 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules/sequelize/lib/sequelize.js:242:13
0|tars-nod | Wed, 26 Sep 2018 09:58:24 GMT koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md at app.js:45:5
0|tars-nod | Mysql connection err { SequelizeConnectionRefusedError: connect ECONNREFUSED 192.168.23.142:3306
0|tars-nod |     at Utils.Promise.tap.then.catch.err (/root/tars/web/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:139:19)
0|tars-nod |     at tryCatcher (/root/tars/web/node_modules/bluebird/js/release/util.js:16:23)
0|tars-nod |     at Promise._settlePromiseFromHandler (/root/tars/web/node_modules/bluebird/js/release/promise.js:512:31)
0|tars-nod |     at Promise._settlePromise (/root/tars/web/node_modules/bluebird/js/release/promise.js:569:18)
0|tars-nod |     at Promise._settlePromise0 (/root/tars/web/node_modules/bluebird/js/release/promise.js:614:10)
0|tars-nod |     at Promise._settlePromises (/root/tars/web/node_modules/bluebird/js/release/promise.js:690:18)
0|tars-nod |     at _drainQueueStep (/root/tars/web/node_modules/bluebird/js/release/async.js:138:12)
0|tars-nod |     at _drainQueue (/root/tars/web/node_modules/bluebird/js/release/async.js:131:9)
0|tars-nod |     at Async._drainQueues (/root/tars/web/node_modules/bluebird/js/release/async.js:147:5)
0|tars-nod |     at Immediate.Async.drainQueues (/root/tars/web/node_modules/bluebird/js/release/async.js:17:14)
0|tars-nod |     at Immediate.args.(anonymous function) (/root/.nvm/versions/node/v8.11.3/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)
0|tars-nod |     at runCallback (timers.js:810:20)
0|tars-nod |     at tryOnImmediate (timers.js:768:5)
0|tars-nod |     at processImmediate [as _immediateCallback] (timers.js:745:5)
0|tars-nod |   name: 'SequelizeConnectionRefusedError',
0|tars-nod |   parent: 
0|tars-nod |    { Error: connect ECONNREFUSED 192.168.23.142:3306
0|tars-nod |     at Object._errnoException (util.js:992:11)
0|tars-nod |     at _exceptionWithHostPort (util.js:1014:20)
0|tars-nod |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
0|tars-nod |      code: 'ECONNREFUSED',
0|tars-nod |      errno: 'ECONNREFUSED',
0|tars-nod |      syscall: 'connect',
0|tars-nod |      address: '192.168.23.142',
0|tars-nod |      port: 3306,
0|tars-nod |      fatal: true },
0|tars-nod |   original: 
0|tars-nod |    { Error: connect ECONNREFUSED 192.168.23.142:3306
0|tars-nod |     at Object._errnoException (util.js:992:11)
0|tars-nod |     at _exceptionWithHostPort (util.js:1014:20)
0|tars-nod |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
0|tars-nod |      code: 'ECONNREFUSED',
0|tars-nod |      errno: 'ECONNREFUSED',
0|tars-nod |      syscall: 'connect',
0|tars-nod |      address: '192.168.23.142',
0|tars-nod |      port: 3306,
0|tars-nod |      fatal: true } }
0|tars-nod | Mysql connection err { SequelizeConnectionRefusedError: connect ECONNREFUSED 192.168.23.142:3306
0|tars-nod |     at Utils.Promise.tap.then.catch.err (/root/tars/web/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:139:19)
0|tars-nod |     at tryCatcher (/root/tars/web/node_modules/bluebird/js/release/util.js:16:23)
0|tars-nod |     at Promise._settlePromiseFromHandler (/root/tars/web/node_modules/bluebird/js/release/promise.js:512:31)
0|tars-nod |     at Promise._settlePromise (/root/tars/web/node_modules/bluebird/js/release/promise.js:569:18)
0|tars-nod |     at Promise._settlePromise0 (/root/tars/web/node_modules/bluebird/js/release/promise.js:614:10)
0|tars-nod |     at Promise._settlePromises (/root/tars/web/node_modules/bluebird/js/release/promise.js:690:18)
0|tars-nod |     at _drainQueueStep (/root/tars/web/node_modules/bluebird/js/release/async.js:138:12)
0|tars-nod |     at _drainQueue (/root/tars/web/node_modules/bluebird/js/release/async.js:131:9)
0|tars-nod |     at Async._drainQueues (/root/tars/web/node_modules/bluebird/js/release/async.js:147:5)
0|tars-nod |     at Immediate.Async.drainQueues (/root/tars/web/node_modules/bluebird/js/release/async.js:17:14)
0|tars-nod |     at Immediate.args.(anonymous function) (/root/.nvm/versions/node/v8.11.3/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)
0|tars-nod |     at runCallback (timers.js:810:20)
0|tars-nod |     at tryOnImmediate (timers.js:768:5)
0|tars-nod |     at processImmediate [as _immediateCallback] (timers.js:745:5)
0|tars-nod |   name: 'SequelizeConnectionRefusedError',
0|tars-nod |   parent: 
0|tars-nod |    { Error: connect ECONNREFUSED 192.168.23.142:3306
0|tars-nod |     at Object._errnoException (util.js:992:11)
0|tars-nod |     at _exceptionWithHostPort (util.js:1014:20)
0|tars-nod |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
0|tars-nod |      code: 'ECONNREFUSED',
0|tars-nod |      errno: 'ECONNREFUSED',
0|tars-nod |      syscall: 'connect',
0|tars-nod |      address: '192.168.23.142',
0|tars-nod |      port: 3306,
0|tars-nod |      fatal: true },
0|tars-nod |   original: 
0|tars-nod |    { Error: connect ECONNREFUSED 192.168.23.142:3306
0|tars-nod |     at Object._errnoException (util.js:992:11)
0|tars-nod |     at _exceptionWithHostPort (util.js:1014:20)
0|tars-nod |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
0|tars-nod |      code: 'ECONNREFUSED',
0|tars-nod |      errno: 'ECONNREFUSED',
0|tars-nod |      syscall: 'connect',
0|tars-nod |      address: '192.168.23.142',
0|tars-nod |      port: 3306,
0|tars-nod |      fatal: true } }
0|tars-nod | error: 192.168.23.1||TreeController.js:30|[listTree] SequelizeConnectionRefusedError: connect ECONNREFUSED 192.168.23.142:3306
0|tars-nod |     at Utils.Promise.tap.then.catch.err (/root/tars/web/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:139:19)
0|tars-nod |     at tryCatcher (/root/tars/web/node_modules/bluebird/js/release/util.js:16:23)
0|tars-nod |     at Promise._settlePromiseFromHandler (/root/tars/web/node_modules/bluebird/js/release/promise.js:512:31)
0|tars-nod |     at Promise._settlePromise (/root/tars/web/node_modules/bluebird/js/release/promise.js:569:18)
0|tars-nod |     at Promise._settlePromise0 (/root/tars/web/node_modules/bluebird/js/release/promise.js:614:10)
0|tars-nod |     at Promise._settlePromises (/root/tars/web/node_modules/bluebird/js/release/promise.js:690:18)
0|tars-nod |     at _drainQueueStep (/root/tars/web/node_modules/bluebird/js/release/async.js:138:12)
0|tars-nod |     at _drainQueue (/root/tars/web/node_modules/bluebird/js/release/async.js:131:9)
0|tars-nod |     at Async._drainQueues (/root/tars/web/node_modules/bluebird/js/release/async.js:147:5)
0|tars-nod |     at Immediate.Async.drainQueues (/root/tars/web/node_modules/bluebird/js/release/async.js:17:14)
0|tars-nod |     at Immediate.args.(anonymous function) (/root/.nvm/versions/node/v8.11.3/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)
0|tars-nod |     at runCallback (timers.js:810:20)
0|tars-nod |     at tryOnImmediate (timers.js:768:5)
0|tars-nod |     at processImmediate [as _immediateCallback] (timers.js:745:5)  
0|tars-nod | error: 192.168.23.1||TreeController.js:30|[listTree] SequelizeConnectionError: Unknown or incorrect time zone: '+-4:00'
0|tars-nod |     at Utils.Promise.tap.then.catch.err (/root/tars/web/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:149:19)
0|tars-nod |     at tryCatcher (/root/tars/web/node_modules/bluebird/js/release/util.js:16:23)
0|tars-nod |     at Promise._settlePromiseFromHandler (/root/tars/web/node_modules/bluebird/js/release/promise.js:512:31)
0|tars-nod |     at Promise._settlePromise (/root/tars/web/node_modules/bluebird/js/release/promise.js:569:18)
0|tars-nod |     at Promise._settlePromise0 (/root/tars/web/node_modules/bluebird/js/release/promise.js:614:10)
0|tars-nod |     at Promise._settlePromises (/root/tars/web/node_modules/bluebird/js/release/promise.js:690:18)
0|tars-nod |     at _drainQueueStep (/root/tars/web/node_modules/bluebird/js/release/async.js:138:12)
0|tars-nod |     at _drainQueue (/root/tars/web/node_modules/bluebird/js/release/async.js:131:9)
0|tars-nod |     at Async._drainQueues (/root/tars/web/node_modules/bluebird/js/release/async.js:147:5)
0|tars-nod |     at Immediate.Async.drainQueues (/root/tars/web/node_modules/bluebird/js/release/async.js:17:14)
0|tars-nod |     at Immediate.args.(anonymous function) (/root/.nvm/versions/node/v8.11.3/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)
0|tars-nod |     at runCallback (timers.js:810:20)
0|tars-nod |     at tryOnImmediate (timers.js:768:5)
0|tars-nod |     at processImmediate [as _immediateCallback] (timers.js:745:5)  
0|tars-nod | error: 192.168.23.1||TreeController.js:30|[listTree] SequelizeConnectionError: Unknown or incorrect time zone: '+-4:00'
0|tars-nod |     at Utils.Promise.tap.then.catch.err (/root/tars/web/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:149:19)
0|tars-nod |     at tryCatcher (/root/tars/web/node_modules/bluebird/js/release/util.js:16:23)
0|tars-nod |     at Promise._settlePromiseFromHandler (/root/tars/web/node_modules/bluebird/js/release/promise.js:512:31)
0|tars-nod |     at Promise._settlePromise (/root/tars/web/node_modules/bluebird/js/release/promise.js:569:18)
0|tars-nod |     at Promise._settlePromise0 (/root/tars/web/node_modules/bluebird/js/release/promise.js:614:10)
0|tars-nod |     at Promise._settlePromises (/root/tars/web/node_modules/bluebird/js/release/promise.js:690:18)
0|tars-nod |     at _drainQueueStep (/root/tars/web/node_modules/bluebird/js/release/async.js:138:12)
0|tars-nod |     at _drainQueue (/root/tars/web/node_modules/bluebird/js/release/async.js:131:9)
0|tars-nod |     at Async._drainQueues (/root/tars/web/node_modules/bluebird/js/release/async.js:147:5)
0|tars-nod |     at Immediate.Async.drainQueues (/root/tars/web/node_modules/bluebird/js/release/async.js:17:14)
0|tars-nod |     at Immediate.args.(anonymous function) (/root/.nvm/versions/node/v8.11.3/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)
0|tars-nod |     at runCallback (timers.js:810:20)
0|tars-nod |     at tryOnImmediate (timers.js:768:5)
0|tars-nod |     at processImmediate [as _immediateCallback] (timers.js:745:5)  
0|tars-nod | error: 192.168.23.1||TreeController.js:30|[listTree] SequelizeConnectionError: Unknown or incorrect time zone: '+-4:00'
0|tars-nod |     at Utils.Promise.tap.then.catch.err (/root/tars/web/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:149:19)
0|tars-nod |     at tryCatcher (/root/tars/web/node_modules/bluebird/js/release/util.js:16:23)
0|tars-nod |     at Promise._settlePromiseFromHandler (/root/tars/web/node_modules/bluebird/js/release/promise.js:512:31)
0|tars-nod |     at Promise._settlePromise (/root/tars/web/node_modules/bluebird/js/release/promise.js:569:18)
0|tars-nod |     at Promise._settlePromise0 (/root/tars/web/node_modules/bluebird/js/release/promise.js:614:10)
0|tars-nod |     at Promise._settlePromises (/root/tars/web/node_modules/bluebird/js/release/promise.js:690:18)
0|tars-nod |     at _drainQueueStep (/root/tars/web/node_modules/bluebird/js/release/async.js:138:12)
0|tars-nod |     at _drainQueue (/root/tars/web/node_modules/bluebird/js/release/async.js:131:9)
0|tars-nod |     at Async._drainQueues (/root/tars/web/node_modules/bluebird/js/release/async.js:147:5)
0|tars-nod |     at Immediate.Async.drainQueues (/root/tars/web/node_modules/bluebird/js/release/async.js:17:14)
0|tars-nod |     at Immediate.args.(anonymous function) (/root/.nvm/versions/node/v8.11.3/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)
0|tars-nod |     at runCallback (timers.js:810:20)
0|tars-nod |     at tryOnImmediate (timers.js:768:5)
0|tars-nod |     at processImmediate [as _immediateCallback] (timers.js:745:5)  
0|tars-nod | error: 192.168.23.1||TreeController.js:30|[listTree] SequelizeConnectionError: Unknown or incorrect time zone: '+-4:00'
0|tars-nod |     at Utils.Promise.tap.then.catch.err (/root/tars/web/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:149:19)
0|tars-nod |     at tryCatcher (/root/tars/web/node_modules/bluebird/js/release/util.js:16:23)
0|tars-nod |     at Promise._settlePromiseFromHandler (/root/tars/web/node_modules/bluebird/js/release/promise.js:512:31)
0|tars-nod |     at Promise._settlePromise (/root/tars/web/node_modules/bluebird/js/release/promise.js:569:18)
0|tars-nod |     at Promise._settlePromise0 (/root/tars/web/node_modules/bluebird/js/release/promise.js:614:10)
0|tars-nod |     at Promise._settlePromises (/root/tars/web/node_modules/bluebird/js/release/promise.js:690:18)
0|tars-nod |     at _drainQueueStep (/root/tars/web/node_modules/bluebird/js/release/async.js:138:12)
0|tars-nod |     at _drainQueue (/root/tars/web/node_modules/bluebird/js/release/async.js:131:9)
0|tars-nod |     at Async._drainQueues (/root/tars/web/node_modules/bluebird/js/release/async.js:147:5)
0|tars-nod |     at Immediate.Async.drainQueues (/root/tars/web/node_modules/bluebird/js/release/async.js:17:14)
0|tars-nod |     at Immediate.args.(anonymous function) (/root/.nvm/versions/node/v8.11.3/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)
0|tars-nod |     at runCallback (timers.js:810:20)
0|tars-nod |     at tryOnImmediate (timers.js:768:5)
0|tars-nod |     at processImmediate [as _immediateCallback] (timers.js:745:5)

**Comment by iiCircle** [comment]
[root@localhost web]# pm2 logs tars-node-web 
[TAILING] Tailing last 15 lines for [tars-node-web] process (change the value with --lines option)
/root/.pm2/logs/tars-node-web-out.log last 15 lines:
0|tars-nod | info: www:34|Server has been started successfully 

/root/.pm2/logs/tars-node-web-error.log last 15 lines:
0|tars-nod | error: 192.168.23.1||TreeController.js:30|[listTree] SequelizeConnectionError: Unknown or incorrect time zone: '+-4:00'
0|tars-nod |     at Utils.Promise.tap.then.catch.err (/root/tars/web/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:149:19)
0|tars-nod |     at tryCatcher (/root/tars/web/node_modules/bluebird/js/release/util.js:16:23)
0|tars-nod |     at Promise._settlePromiseFromHandler (/root/tars/web/node_modules/bluebird/js/release/promise.js:512:31)
0|tars-nod |     at Promise._settlePromise (/root/tars/web/node_modules/bluebird/js/release/promise.js:569:18)
0|tars-nod |     at Promise._settlePromise0 (/root/tars/web/node_modules/bluebird/js/release/promise.js:614:10)
0|tars-nod |     at Promise._settlePromises (/root/tars/web/node_modules/bluebird/js/release/promise.js:690:18)
0|tars-nod |     at _drainQueueStep (/root/tars/web/node_modules/bluebird/js/release/async.js:138:12)
0|tars-nod |     at _drainQueue (/root/tars/web/node_modules/bluebird/js/release/async.js:131:9)
0|tars-nod |     at Async._drainQueues (/root/tars/web/node_modules/bluebird/js/release/async.js:147:5)
0|tars-nod |     at Immediate.Async.drainQueues (/root/tars/web/node_modules/bluebird/js/release/async.js:17:14)
0|tars-nod |     at Immediate.args.(anonymous function) (/root/.nvm/versions/node/v8.11.3/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)
0|tars-nod |     at runCallback (timers.js:810:20)
0|tars-nod |     at tryOnImmediate (timers.js:768:5)
0|tars-nod |     at processImmediate [as _immediateCallback] (timers.js:745:5)

**Comment by apacoco9861** [comment]
Hi,
I got the same errors. tars db account access denied. May I know where to fix while I followed the procedures provides, unable to locate where to set.
![image](https://user-images.githubusercontent.com/5441738/46183957-fa83e200-c305-11e8-932f-63ea13b0597e.png)

Many thanks,

Paco

0|tars-nod |   original:
0|tars-nod |    { Error: Access denied for user 'tars'@'web-tars-2-113' (using password: YES)
0|tars-nod |     at Packet.asError (/root/TarsWeb/node_modules/mysql2/lib/packets/packet.js:714:13)
0|tars-nod |     at ClientHandshake.Command.execute (/root/TarsWeb/node_modules/mysql2/lib/commands/command.js:28:22)
0|tars-nod |     at Connection.handlePacket (/root/TarsWeb/node_modules/mysql2/lib/connection.js:513:28)
0|tars-nod |     at PacketParser.onPacket (/root/TarsWeb/node_modules/mysql2/lib/connection.js:81:16)
0|tars-nod |     at PacketParser.executeStart (/root/TarsWeb/node_modules/mysql2/lib/packet_parser.js:76:14)
0|tars-nod |     at Socket.<anonymous> (/root/TarsWeb/node_modules/mysql2/lib/connection.js:89:29)
0|tars-nod |     at emitOne (events.js:116:13)
0|tars-nod |     at Socket.emit (events.js:211:7)
0|tars-nod |     at addChunk (_stream_readable.js:263:12)
0|tars-nod |     at readableAddChunk (_stream_readable.js:250:11)
0|tars-nod |     at Socket.Readable.push (_stream_readable.js:208:10)
0|tars-nod |     at TCP.onread (net.js:597:20)
0|tars-nod |      code: 'ER_ACCESS_DENIED_ERROR',
0|tars-nod |      errno: 1045,
0|tars-nod |      sqlState: '28000',

**Comment by iiCircle** [comment]
I hava the same errors ···  I haven't solved it yet. If you know how to solve it, tell me about it.

**Comment by apacoco9861** [comment]
![image](https://user-images.githubusercontent.com/5441738/46184121-b0e7c700-c306-11e8-8d93-970ef68b0d0c.png)
I have fixed the issue by modifying the webConf.js password, as the guideline just replace the hostname and ip, not mentioned the password inside the configuration file.

**Comment by iiCircle** [comment]
/**
 * Tencent is pleased to support the open source community by making Tars available.
 *
 * Copyright (C) 2016THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the BSD 3-Clause License (the "License"); you may not use this file except 
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/BSD-3-Clause
 *
 * Unless required by applicable law or agreed to in writing, software distributed 
 * under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR 
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the 
 * specific language governing permissions and limitations under the License.
 */
var path = require('path');

module.exports = {
    dbConf: {
        host: '192.168.23.142',       // 数据库地址
        port: '3306',            // 数据库端口
        user: 'tars',            // 用户名
        password: 'tars2015',       // 密码
        charset: 'utf8_bin',     // 数据库编码
        pool: {
            max: 10,             // 连接池中最大连接数量
            min: 0,              // 连接池中最小连接数量
            idle: 10000          // 如果一个线程 10 秒钟内没有被使用过的话，那么就释放线程
        }
    },
    webConf: {
        port: 3000,              //服务启动端口
        loggerPath: path.join(__dirname, '../log'),    //本地日志的目录
        logFileKeepDays: '1',         //日志保留时间
        defaultLanguage: 'cn',    //cn 或 en ，用户默认的语言环境
    },
    kafkaConf : {
        enable : false,
        kafkaHost : 'localhost:9092',
        zkHost : 'localhost:2181',
        topic : 'tarsTask',
        maxCount : 100              // 后台并行处理的最大任务数
    },
    pkgUploadPath : {
        path : '/usr/local/app/patchs/tars.upload'
    },
    //防洪水攻击配置
    limitConf: {
        enableLimit: true,            //是否启用此配置
        limit: 5000,                  //限制访问的次数
        interval: 1000 * 60 * 10,     //限制的时间间隔，单位为ms，如：1小时内限制访问5000次
        whilteList: [],               //白名单IP
        blackList: []                 //黑名单IP
    }
};

**Comment by iiCircle** [comment]
Is that so? Thank you
