### ISSUE TITLE
接口调试: 上传tars文件 显示 " 错误: 系统内部错误 "

### ISSUE THREAD

**Issue by longfei9527** [TarsCloud/Tars#352]
接口调试: 上传tars文件 显示 " 错误: 系统内部错误 " #

pm2 logs --err日志: 

`0|tars-node-web  | error: 192.168.195.1||InfTestController.js:69|[uploadTarsFile]: Error: Cannot find type["String"]
0|tars-node-web  |     at TarsParser.getType (/home/py/tarspackage/Tars/web/app/service/infTest/TarsParser/TarsParser.js:345:27)
0|tars-node-web  |     at TarsParser.parseFun (/home/py/tarspackage/Tars/web/app/service/infTest/TarsParser/TarsParser.js:226:34)
0|tars-node-web  |     at TarsParser.parseInterface (/home/py/tarspackage/Tars/web/app/service/infTest/TarsParser/TarsParser.js:109:18)
0|tars-node-web  |     at TarsParser.parseModule (/home/py/tarspackage/Tars/web/app/service/infTest/TarsParser/TarsParser.js:60:26)
0|tars-node-web  |     at TarsParser.parseFile (/home/py/tarspackage/Tars/web/app/service/infTest/TarsParser/TarsParser.js:30:22)
0|tars-node-web  |     at getContext (/home/py/tarspackage/Tars/web/app/service/infTest/InfTestService.js:53:12)
0|tars-node-web  |     at <anonymous>  
`

报错截图:

![1](https://user-images.githubusercontent.com/29699411/49424579-fe385700-f7d5-11e8-808e-85f86bfbd5de.png)

![2](https://user-images.githubusercontent.com/29699411/49424582-00021a80-f7d6-11e8-9dfe-36562b3997b4.png)

**Comment by longfei9527** [comment]
1 : .tars 文件, 里面的数据类型要严格区分大小写, 要符合Tars的数据类型的结构, 不然就报上面的错.
2 : 接口调试无发返回调试数据, web 的 TarsClient.js 代码存在bug, 进入 git 下来的Tars目录下执行下列命令, sed -i "s/setName ? setName : '')/setName ? setName : '', {})/g" web/app/service/infTest/TarsClient.js
3 : 如果执行无效, 手动 vim /home/py/tarspackage/Tars/web/app/service/infTest/TarsClient.js 
(注 : 具体目录请根据个人安装路径 )
