### ISSUE TITLE
Status Monitor and Property Monitor accor System error

### ISSUE THREAD

**Issue by better629** [TarsCloud/Tars#404]
### What language are you using?
 C+
 
### What operating system (Linux, Ubuntu, …) and version?
ubuntu 18
 
### What runtime / compiler are you using (e.g. jdk version or version of gcc)
 gcc 4.8
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

When click the 【Status Monitor】and 【 Property Monitor】，under error occur：
use the master code of Tars
`
error: MonitorPropertyService.js:67|[AdminService.getEndpoints]: tars.tarsqueryproperty.NoTarsObj not found
error: MonitorPropertyService.js:67|[AdminService.getEndpoints]: tars.tarsqueryproperty.NoTarsObj not found
error: 192.168.4.203|admin|MonitorController.js:58|TypeError: Cannot read property 'keys' of undefined
    at mergeKey (***/Tars/web/app/service/monitor/MonitorPropertyService.js:129:28)
    at merge (***/Tars/web/app/service/monitor/MonitorPropertyService.js:77:15)
    at Object.MonitorPropertyService.getTARSPropertyMonitorData (**/Tars/web/app/service/monitor/MonitorPropertyService.js:27:12)
    at <anonymous>
error: MonitorStatService.js:72|[AdminService.getEndpoints]: tars.tarsquerystat.NoTarsObj not found
error: MonitorStatService.js:72|[AdminService.getEndpoints]: tars.tarsquerystat.NoTarsObj not found
error: 192.168.4.203|admin|MonitorController.js:47|TypeError: Cannot read property 'keys' of undefined
    at mergeKey (**/Tars/web/app/service/monitor/MonitorStatService.js:162:28)
    at merge (**/Tars/web/app/service/monitor/MonitorStatService.js:82:15)
    at Object.MonitorStatService.getTARSStatMonitorData (**/Tars/web/app/service/monitor/MonitorStatService.js:27:12)
    at <anonymous>
`

**Comment by better629** [comment]
Above errors are duing to that I have't deploy tarsquerystat and tarspropertystat. But when I deployed, an another error occurs:
Table 'tars_stat.tars_stat_2019052100' doesn't exist

**Comment by better629** [comment]
There are some Error in tarsstat.log also in tarsquerystat.log

`
2019-05-22 15:47:46|24844|ERROR|[TARS] write to remote log server error:server unknown exception: ret:-7 msg:[ServantProxy::invoke errno:-7,info:,servant:tars.tarslog.LogObj,func:loggerbyInfo,reqid:0]: buffer size:1
2019-05-22 15:47:47|24841|ERROR|[TARS][QueryEpBase::doEndpoints, callback activeEps is empty,objname:tars.tarslog.LogObj]
2019-05-22 15:47:49|24841|ERROR|[TARS][ObjectProxy::doTimeout, objname:tars.tarslog.LogObj, queue timeout error]
2019-05-22 15:47:49|24844|ERROR|[TARS] write to remote log server error:server unknown exception: ret:-7 msg:[ServantProxy::invoke errno:-7,info:,servant:tars.tarslog.LogObj,func:loggerbyInfo,reqid:0]: buffer size:1
2019-05-22 15:47:52|24841|ERROR|[TARS][ObjectProxy::doTimeout, objname:tars.tarslog.LogObj, queue timeout error]
2019-05-22 15:47:52|24844|ERROR|[TARS] write to remote log server error:server unknown exception: ret:-7 msg:[ServantProxy::invoke errno:-7,info:,servant:tars.tarslog.LogObj,func:loggerbyInfo,reqid:0]: buffer size:1
`

**Comment by mrseanchow** [comment]
重新配置 web/config/tars.conf 的client 节点下locator  ，地址不能为 127.0.0.1
